version: "3.7"

services:

  userge:

      build:

        context: https://github.com/Thegreatfoxxgoddess/paimon

      depends_on:

        - mongo

      restart: on-failure

      environment:

          DATABASE_URL: mongodb+srv://alicia:paimon@cluster0.0lamr.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
          
      env_file:

        - config.env

  mongo:

      image: mongo

      volumes:

        - mongo_userge:/data/db

      environment:

        MONGO_INITDB_ROOT_USERNAME: root

        MONGO_INITDB_ROOT_PASSWORD: example

volumes:

  mongo_userge:
