version: "3.7"

services:

  userge:

      build:

        context: your repo link.git#branch

      depends_on:

        - mongo

      restart: on-failure

      environment:

          DATABASE_URL: your db url here
          
      env_file:

        - config.env

  mongo:

      image: mongo

      volumes:

        - mongo_userge:/data/db

      environment:

        MONGO_INITDB_ROOT_USERNAME: root

        MONGO_INITDB_ROOT_PASSWORD: example

volumes:

  mongo_userge:
